### ISSUE TITLE
Repair link on Developer portal

### ISSUE THREAD

**Issue by banterCZ** [wultra/enrollment-server#1061]
On [this link](https://developers.wultra.com/components/enrollment-server/1.7.x/documentation/Operation-Extensions) the links to "Implementation tutorials" don't work, highlighted on the print screen in the attachment. 

![Image](https://github.com/wultra/enrollment-server/assets/113174804/000c6233-8982-4632-83e1-2337e9aee290)

**Comment by banterCZ** [comment]
@OliverJanstaWultra you may review develop, https://developers.wultra.com/components/enrollment-server/develop/documentation/
The backport is in progress.

**Comment by OliverJanstaWultra** [comment]
Yes, it looks good to me.
