### ISSUE TITLE
Use consistent DocumentMetadata

### ISSUE THREAD

**Issue by saalistaja** [wultra/enrollment-server#156]
We should use consistent data, currently two fields (type, side) or only in one entity. Consider using one common `DocumentMetadata`.

https://github.com/wultra/enrollment-server/blob/issues/88-customer-identification-verification/enrollment-server-api-model/src/main/java/com/wultra/app/enrollmentserver/api/model/response/DocumentSubmitResponse.java

https://github.com/wultra/enrollment-server/blob/issues/88-customer-identification-verification/enrollment-server-api-model/src/main/java/com/wultra/app/enrollmentserver/api/model/response/DocumentStatusResponse.java

**Comment by kober32** [comment]
For frontend purposes - I need https://github.com/wultra/enrollment-server/blob/issues/88-customer-identification-verification/enrollment-server-api-model/src/main/java/com/wultra/app/enrollmentserver/api/model/response/DocumentSubmitResponse.java version of the metadata.
