### ISSUE TITLE
ZenId provider changes date serialization for Mobile Token

### ISSUE THREAD

**Issue by romanstrobl** [wultra/enrollment-server#181]
The following ObjectMapper configuration is overriden by ObjectMapper configuration in code:

Configuration of property `spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssZ`:
https://github.com/wultra/enrollment-server/blob/c79f82aee95445010d2b68ca3d8ff9da747e3203/enrollment-server/src/main/resources/application.properties#L61

This configuration is overriden by:
https://github.com/wultra/enrollment-server/blob/c79f82aee95445010d2b68ca3d8ff9da747e3203/enrollment-server/src/main/java/com/wultra/app/docverify/zenid/config/ZenidConfig.java#L88

However, this behavior breaks compatiblity with with Wultra Mobile Token application.

Expected date format by Mobile Token:
```
2022-04-12T18:17:59+0000
```

Overriden date format by Zen ID provider:
```
2022-04-12T18:15:38.843+00:00
```

Mobile Token works fine when I switch to `mock` provider, because the configuration is not overriden.

**Comment by saalistaja** [comment]
Resolved by #178
