### ISSUE TITLE
Review autowiring after application split

### ISSUE THREAD

**Issue by romanstrobl** [wultra/enrollment-server#239]
I suspect that there is much more autowiring from `enrollment-server` of onboarding classes than necessary after application split. We should clean this up.

**Comment by banterCZ** [comment]
It is seen https://github.com/wultra/enrollment-server/blob/develop/enrollment-server/src/main/java/com/wultra/app/enrollmentserver/onboarding/activation/OnboardingComponentsConfiguration.java

I guess that it should be configured conditionally (same for `ActivationProcessService`). It does not make sense to initialize these beans for environments without onboarding.

**Comment by banterCZ** [comment]
The big cleanup is realized in #254

**Comment by romanstrobl** [comment]
I found no issues, we can close the issue.
