### ISSUE TITLE
Clarify use of: @Type(type = "org.hibernate.type.TextType")

### ISSUE THREAD

**Issue by petrdvorak** [wultra/enrollment-server#345]
... I am still not clear why this annotation is required. The fact it points to Hibernate is a bit suspicious.

**Comment by banterCZ** [comment]
Investigation in progress, an interesting article https://www.jpa-buddy.com/blog/how-to-store-text-in-postgresql-tips-tricks-and-traps/

**Comment by banterCZ** [comment]
The root cause is that `PostgreSQLDialect` handles `CLOB` as oid. That is why we got `PSQLException: Bad value for type long`. Annotations `@Lob` and `@Type` will be completely removed in #346 and tested in PG and Oracle as well.
