### ISSUE TITLE
Publish Inbox API for Mobile Token

### ISSUE THREAD

**Issue by romanstrobl** [wultra/enrollment-server#493]
Publish an Inbox API for Mobile Token as a facade for Push Server REST API with following endpoints:
- POST `/api/inbox/count` - get count of unread messages in inbox
- POST `/api/inbox/message/list` - get a page with messages with given page number and size
- POST `/api/inbox/message/detail` - get detail of a message with given message identifier
- POST `/api/inbox/message/read` - mark a message with given message identifier as read
- POST `/api/inbox/message/read-all` - mark all messages as read for user

The reason of using `POST` for all these endpoints is that we do not want to expose any sensitive details in the URL and for consistency with e.g. POST `/api/auth/token/app/operation/list`.

**Comment by kober32** [comment]
`/api/inbox/count` - I would prefer `/api/inbox/unread` to be more clear about it

**Comment by romanstrobl** [comment]
We probably want to return both read and unread counts in the endpoint. To be confirmed...
