### ISSUE TITLE
Suspicious filename records in table es_document_verification

### ISSUE THREAD

**Issue by romanstrobl** [wultra/enrollment-server#498]
Data from a run through onboarding:

```
powerauth=# select type, provider_name, filename from es_document_verification where identity_verification_id='a9f69d81-7007-478a-9925-a4666045dd9b';
      type       | provider_name |                            filename                            
-----------------+---------------+----------------------------------------------------------------
 SELFIE_PHOTO    | zenid         | person_photo_from_id.jpg
 ID_CARD         | zenid         | 4BAC5315-0EEA-4344-A385-A987ACB8D57B/id_card_front.jpg
 ID_CARD         | zenid         | 4BAC5315-0EEA-4344-A385-A987ACB8D57B/id_card_back.jpg
 DRIVING_LICENSE | zenid         | 32B14D8C-BBB4-417D-8C6A-3B82F0E3B6EE/driving_license_front.jpg
```

I do not think that the first row is correct, both `provider_name` and `filename` are suspicious. The document type is `SELFIE_PHOTO` and the `person_photo_from_id.jpg` filename is generated in code by iProov provider. So is this a photo extracted from ID or a selfie photo?

**Comment by banterCZ** [comment]
Filename is changed (to show source), the provider name stays (to show place where the image is stored).

`filename=person_photo_from_iProov.jpg, providerName=zenid`
