### ISSUE TITLE
Invalid state when app gets closed during onboarding

### ISSUE THREAD

**Issue by romanstrobl** [wultra/enrollment-server#512]
In case both sides of ID card get rejected, the following invalid state occurs (see log messages).

Both documents which were submitted for verification are in state `REJECTED`, however the application claims that there are not enough documents to change the identity verification state. When the application is restarted at this point the process cannot be completed and the user just sees the progress wheel.

```
Nov 08 18:34:45 PowerAuth-Dev tomcat9[3023321]: 2022-11-08 18:34:45.053  INFO 3023321 --- [   scheduling-1] .a.o.i.s.v.VerificationProcessingService : Finished verification of DocumentVerificationEntity(id=7a4f9d3f-51e7-4a6c-a3ee-0d31323a44a3, type=ID_CARD, uploadId=f18b6625f2a66358ef482dd4ef834c81) with status: REJECTED, OwnerId(activationId=2554096f-0bbb-465e-83d9-e87d98ed49ab, userId=mockuser_258963)
Nov 08 18:34:45 PowerAuth-Dev tomcat9[3023321]: 2022-11-08 18:34:45.054  INFO 3023321 --- [   scheduling-1] .a.o.i.s.v.VerificationProcessingService : Finished verification of DocumentVerificationEntity(id=009accec-3c21-47e3-8321-534b6ea8fccc, type=ID_CARD, uploadId=4a5188e618feed607e5eff4261a61478) with status: REJECTED, OwnerId(activationId=2554096f-0bbb-465e-83d9-e87d98ed49ab, userId=mockuser_258963)
Nov 08 18:34:45 PowerAuth-Dev tomcat9[3023321]: 2022-11-08 18:34:45.055 DEBUG 3023321 --- [   scheduling-1] c.w.a.o.s.g.d.RequiredDocumentTypesCheck : There is not enough accepted document yet for identity verification ID: 34967332-1f2e-4773-af27-b5ff09ac6254
```

Update: The same problem occurs when first document is `ACCEPTED`, `REJECTED` or `FAILED` and the app is restarted, because identity verification status does not correspond to document status.

**Comment by kober32** [comment]
Just to add, fronted is receiving a `DOCUMENT_VERIFICATION` and `IN_PROGRESS` after uploading ID card (2 sides), which is wrong. The state machine should be in the `DOCUMENT_UPLOAD` `IN_PROGRESS` as the lucid chart flow states, otherwise, this is a dead-end as the backend is waiting for more documents and the application is waiting for an evaluation to finish...
