### ISSUE TITLE
Missing package-lock.json

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/enrollment-server#661]
The internal tool is missing package-lock.json so Dependabot cannot update dependencies. Add package-lock.json to fix it.

**Comment by romanstrobl** [comment]
I doubt that this is a correct intention. We should rather remove the iProov sample JavaScript application, it should not be present in this repo, do you agree?

**Comment by zcgandcomp** [comment]
The tool is deprecated - deleting - this will also solve Dependabot issue.
