### ISSUE TITLE
Upload presence check photo for failed authentication attempts

### ISSUE THREAD

**Issue by romanstrobl** [wultra/enrollment-server#773]
When the presence check fails, upload the photo even for failed authentication attempts due to the requirements for fraud verification.

The issue is related to: https://github.com/wultra/enrollment-server/issues/761, we should store SCA results correctly, because the photo upload is now used for checking that SCA step succeeded.

**Comment by banterCZ** [comment]
Selfie is still not uploaded when presence check failed.
