### ISSUE TITLE
Improve audit of failed document uploads

### ISSUE THREAD

**Issue by romanstrobl** [wultra/enrollment-server#776]
Only successful document upload is audited.

**Comment by banterCZ** [comment]
It is already audited but the message is a little bit misleading. There is a common method for handling upload and verification results. It should be enough just to differentiate the messages. https://github.com/wultra/enrollment-server/blob/e1523724a6491edfa6c32d5aab26b1fb00426ae2/enrollment-server-onboarding/src/main/java/com/wultra/app/onboardingserver/impl/service/document/DocumentProcessingService.java#L405
