### ISSUE TITLE
Change defaulting of locales for template finding

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/enrollment-server#891]
Currently, if a template is not found for a locale, the English version is used as a default.

This causes an issue when the English version is not set.

Modify the logic - if the template is not found for the requested locale, return any existing template.

**Comment by banterCZ** [comment]
Let's make the order in this way
1) Given language
2) English
3) Any other found language

**Comment by OliverJanstaWultra** [comment]
QA: Create templates that are not in English and try them.

**Comment by kopovan** [comment]
QA OK, the criteria have been met as described above. Tested od PACE, screenshots attached:
<img src="https://github.com/wultra/enrollment-server/assets/135111051/93c78d91-956e-49e0-bb6b-ef7177695b06" width="300" /> <img src="https://github.com/wultra/enrollment-server/assets/135111051/a461fda5-a94d-44bd-81e3-59b555548387" width="300" /> <img src="https://github.com/wultra/enrollment-server/assets/135111051/627c36d6-f330-4954-acbb-a2a4bd74b2d8" width="300" />
