### ISSUE TITLE
Use different error when PAS operation approve fails

### ISSUE THREAD

**Issue by kober32** [wultra/enrollment-server#896]
Discovered during the development by @Hopsaheysa 

Right now, when a client sends a Proximity OTP that is expired or just wrong, the server returns:

```json
{"status":"ERROR","responseObject":{"code":"POWERAUTH_AUTH_FAIL","message":"Authentication failed"}}
```

This is the same error as WRONG PASSWORD, so as of now, the frontend cannot differentiate these cases which leads to a very misleading UX in the app.

We need to be able to know when the PAS _operation approval_ fails. For this use case let's introduce a new error code `OPERATION_FAILED`. 

An invalid signature is already covered by 

```java
@PostMapping("/operation/authorize")
@PowerAuth(resourceId = "/operation/authorize", signatureType = {
        PowerAuthSignatureTypes.POSSESSION,
        PowerAuthSignatureTypes.POSSESSION_KNOWLEDGE,
        PowerAuthSignatureTypes.POSSESSION_BIOMETRY
})
public Response operationApprove(
```

**Comment by OliverJanstaWultra** [comment]
@Hopsaheysa will test it during QR code development
