### ISSUE TITLE
Add parsed user agent to the audit

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/enrollment-server#904]
Followup to https://github.com/wultra/lime-java-core/issues/217 and https://github.com/wultra/lime-java-core/issues/223

For easier audit management we try to parse incoming request and find header `useragent`. 

If the `useragent` is in a known format (currently our Powerauth Networking and PowerAuth SDK) the audit logic will populate

attribute `device` in `additionalData`. i.e. what we are able to parse to the device structure will be parsed to device structure.

example:

```
 "additionalData": {
  "device": {
     "language": "en",
     "manufacturer": "Apple",
     "model": "iPhone 12"
     "os": "iOS/15.7.8",
     "app": {
        "id": "com.wultra.app.MobileToken.multitude.wdev",
        "version": "1.0.0"
    }
  },
...
}
```

The original useragent should be retained - as a failover for parsing and to contain data not included in the parsing logic.

**Comment by jandusil** [comment]
I will take it, @jnpsk

**Comment by jandusil** [comment]
After analysis and discussions with @zcgandcomp, we have identified two potential solutions to address the issue:

**Option A: Changes in Enrollment Server, PAS, Lime Core**
- **Lime Core**: Ensure `Device` implements `Serializable` (completed - see [GitHub Issue 226](https://github.com/wultra/lime-java-core/issues/226)).
- **Enrollment Server**: Implement parsing of `Device` from `UserAgent`, and include it in the `additionalData` property of the relevant DTOs.
- **PAS**: Modify `additionalData` in DTOs from `Map<String, String>` to `Map<String, Object>` for better serialization. Similarly, update `OperationEntity` and `MapToJsonConverter`.

_Test Results for Audit Log Entry_:
``` JSON
{
   "id":"740f2789-86f1-4d6b-be8a-8f079c5de10a",
   "userId":"TestUserV32_e22842f4-7177-47db-bb61-35f0e55b2c61",
   "appId":"PA_Tests",
   "status":"APPROVED",
   "additionalData":{
      "device":{
         "networkVersion":"1.1.7",
         "language":"en",
         "connection":"cellular",
         "product":"com.wultra.app.MobileToken.wtest",
         "version":"2.0.0",
         "platform":"Apple",
         "os":"iOS",
         "osVersion":"16.6.1",
         "model":"iphone12,3"
      },
      "proximity_otp":"05519033"
   },
   "failureCount":0,
   "proximityCheckResult":"SUCCESS",
   "currentTimestamp":"2023-11-12T14:47:31.918+00:00"
}
```

**Option B: Changes in PAS, Lime Core - Preferred Option and current solution**
- **Lime Core**: As above.
- **PAS**: As above, plus include logic to parse `Device` from the `user agent` string in `additionalData` before auditing and saving operation.

_Sample Code for Parsing Device_:
```java
private static void parseDeviceFromUserAgent(Map<String, Object> additionalData) {
    final Object userAgentObject = additionalData.get(ATTR_USER_AGENT);
    if (userAgentObject != null) {
        final UserAgent.Device device = UserAgent.parse(userAgentObject.toString());
        if (device != null) {
            additionalData.put(ATTR_DEVICE, device);
        }
    }
}
```
Considerations for Discussion:
* Do we want `Device` information only in the `audit_log` table, or should it also be part of the `pa_operation`? In the current solution it is included in both.

Link to current proposed solution: https://github.com/wultra/powerauth-server/pull/1125

**Comment by zcgandcomp** [comment]
As discussed on grooming:
- Parsing logic of the `Agent` -> `Device` should be on PAS level.
- As of now do not put redundant information to `pa_signature_audit` / `pa_operation` - the reason is redundancy and increased data storage issue (table `pa_signature_audit` doesn't have any automatic data putging/archiving)

**Comment by jandusil** [comment]
All tasks are finished
