### ISSUE TITLE
Innovatrics PresenceCheckProvider

### ISSUE THREAD

**Issue by banterCZ** [wultra/enrollment-server#908]
- https://innovatrics.github.io/dot-digital-identity-service/?url=https://raw.githubusercontent.com/innovatrics/dot-digital-identity-service/1.27.0/api/swagger.json
- https://developers.innovatrics.com/digital-onboarding/technical/remote/dot-dis/latest/documentation/#_api_reference

**Comment by jnpsk** [comment]
Implementation of the `PresenceCheckProvider` using Innovatrics API

`void initPresenceCheck(OwnerId id, Image photo)`  
Called by the state machine after triggering `/presence-check/init`. The photo comes from document verification provider, by requesting the photo from preferred document. IProov provider uses this function to enroll a user and assign the photo. Innovatrics does not expects a portrait from an ID document at this stage.
Innovatrics API:
- `PUT /liveness` to initiate liveness check

`SessionInfo startPresenceCheck(OwnerId id)`  
Called by the state machine right after `initPresenceCheck()`. IProov provider establishes a session during this call. Innovatrics has multiple types of liveness check which should be specified during a selfie upload.
- `POST /liveness/selfies`  

As an alternative to posting selfies, a binary file produced by Innovatrics SDK can be used.
- `POST /liveness/records`

`PresenceCheckResult getResult(OwnerId id, SessionInfo sessionInfo)`  
Called by the state machine when `/presence-check/submit` is called. IProov provider gets the verification result.  
Innovatrics API:
- `POST /liveness/evaluation` returns level of confidence the selfies contain live person
- `POST /inspect` biometric checks

`void cleanupIdentityData(OwnerId id)`  
Called with `/api/identity/cleanup`. Does nothing when IProov provider is used.
- `DELETE /selfie`
- `DELETE /customer`
- `DELETE /liveness`

**Conclusion:** IProve provider just initiates a session for a direct connection between mobile device and Iproov API. First of all we need to build a proxy between Innovatrics and mobile device to deliver liveness records or selfies. As document verification and liveness detection is handled by the same provider, it is unnecessary to pass a selfie to document provider or pass document portrait to liveness check provider during liveness check process.

*These notes can be changed over time*
