### ISSUE TITLE
AmountAttribute with invalid amount

### ISSUE THREAD

**Issue by banterCZ** [wultra/enrollment-server#970]
The input validation should be improved. Currently, when not a number is passed into `AmountAttribute`, the operation is returned successfully in the list but without that attribute at all (a warning is logged `logger.warn("Invalid number format: {}, skipping the AMOUNT attribute!", amount);`). This is caused by wrong integration, not by user interaction. The integrator has to fix it but should get a clue.

There are two options to handle that:

- Do not return such an operation at all. Unfortunately, the push notification has already been sent.
- Do not fill in the formatted field but the raw one, at least.

A similar situation is for `AmountConversionAttribute` as well.

**Comment by banterCZ** [comment]
Hints to test:
- Current wrong behavior: When _not a number_ is sent to the amount, the attribute is not shown on the mobile token at all.
- Expected behavior: When _not a number_ is sent to the amount, the attribute is shown with `amount=null` and `amountFormatted` should contain the original value.

**Comment by kopovan** [comment]
When sent in the `v2/operations`:
1. `"amount": ""` -> the attribute is not displayed on the phone
2. `"amount": "aaa"` -> the attribute is not displayed on the phone

<img src="https://github.com/wultra/enrollment-server/assets/135111051/c1b101b5-2db9-4fd4-ac4d-fcbc6184a744" width="300" />
