### ISSUE TITLE
Filter out errors from document verification in onboarding

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/enrollment-server#995]
Filter out specific reasons for document rejection in onboarding process - level only generic messages in errors.

i.e. in the errors list return a single error with a generic meaning.

```
"status": "OK",
"responseObject":
{
"status": "IN_PROGRESS",
"documents":
[
{
"filename": "id_card_front.jpg",
"id": "19c84663-b3bb-48f6-b2f4-079ebc6f9910",
"type": "ID_CARD",
"side": "FRONT",
"status": "REJECTED",
"errors": [
"Error verifying the document."

```

**Comment by jnpsk** [comment]
As a result of the change implemented in this issue, the response of `/documents/status` should not contain specific reason of rejection or specific fail reason.

This change can be tested by taking the onboarding process with an invalid personal document (specimen photo) and see if the `/documents/status` does return only "Error verifying the document." as an error, without any detail.

**Comment by OliverJanstaWultra** [comment]
@jnpsk please deploy to env
@kopovan after that please test

**Comment by kopovan** [comment]
retest OK


<img src="https://github.com/wultra/enrollment-server/assets/135111051/5ea383a1-a02b-4d63-84ac-421aab9a8d0e" width="300" />
